// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxvueofqhqfzzdcsotub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4dnVlb2ZxaHFmenpkY3NvdHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzOTIzNjksImV4cCI6MjA1ODk2ODM2OX0.jGVVWxtqR_SngzRELF2jAILmqYEZXGlTP-1hxYBWX0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);